{{- if .Values.uptimeKuma.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uptime-kuma.uptimeKuma.fullname" . }}
  labels:
    {{- include "uptime-kuma.uptimeKuma.labels" . | nindent 4 }}
spec:
  {{- if not .Values.uptimeKuma.autoscaling.enabled }}
  replicas: {{ .Values.uptimeKuma.replicaCount }}
  {{- end }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "uptime-kuma.uptimeKuma.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.uptimeKuma.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "uptime-kuma.uptimeKuma.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.uptimeKuma.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "uptime-kuma.uptimeKuma.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.uptimeKuma.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.uptimeKuma.securityContext | nindent 12 }}
          image: "{{ .Values.uptimeKuma.image.repository }}:{{ .Values.uptimeKuma.image.tag }}"
          imagePullPolicy: {{ .Values.uptimeKuma.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - extra/healthcheck
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
          startupProbe:
            exec:
              command:
                - extra/healthcheck
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 600
          resources:
            {{- toYaml .Values.uptimeKuma.resources | nindent 12 }}
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
          {{- if .Values.uptimeKuma.persistence.enabled }}
            - name: data
              mountPath: /app/data
          {{- end }}
      volumes:
        - name: localtime
          hostPath:
            path: {{ .Values.uptimeKuma.localtime }}
        {{- if .Values.uptimeKuma.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "uptime-kuma.uptimeKuma.persistentVolumeClaim" . }}
        {{- end }}
      {{- with .Values.uptimeKuma.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.uptimeKuma.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.uptimeKuma.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}