{{- if .Values.signal.enabled }}
{{- if .Values.signal.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "uptime-kuma.signal.serviceAccountName" . }}
  labels:
    {{- include "uptime-kuma.signal.labels" . | nindent 4 }}
  {{- with .Values.signal.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
