{{- if .Values.uptimeKuma.enabled }}
{{- if .Values.uptimeKuma.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "uptime-kuma.uptimeKuma.serviceAccountName" . }}
  labels:
    {{- include "uptime-kuma.uptimeKuma.labels" . | nindent 4 }}
  {{- with .Values.uptimeKuma.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
