{{- if .Values.uptimeKuma.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "uptime-kuma.uptimeKuma.fullname" . }}
  labels:
    {{- include "uptime-kuma.uptimeKuma.labels" . | nindent 4 }}
spec:
  type: {{ .Values.uptimeKuma.service.type }}
  ports:
    - port: {{ .Values.uptimeKuma.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "uptime-kuma.uptimeKuma.selectorLabels" . | nindent 4 }}
{{- end }}
