{{- if .Values.signal.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "uptime-kuma.signal.fullname" . }}
  labels:
    {{- include "uptime-kuma.signal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.signal.service.type }}
  ports:
    - port: {{ .Values.signal.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "uptime-kuma.signal.selectorLabels" . | nindent 4 }}
{{- end }}
