uptimeKuma:
  persistence:
    enabled: true
    storageClass: nfs-ssd
    accessModes:
      - ReadWriteMany
  ingresses:
    public:
      enabled: true
      className: "haproxy"
      annotations:
        haproxy-ingress.github.io/allowlist-source-range: "0.0.0.0/0,::/0"
      hosts:
        - host: status.pc-ziegert.de
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - status.pc-ziegert.de
          secretName: pc-ziegert-de-wildcard-cert
    private:
      enabled: true
      className: "haproxy"
      annotations: {}
      hosts:
        - host: uptime-kuma.pc-ziegert.de
          paths:
            - path: /
              pathType: Prefix
        - host: status-internal.pc-ziegert.de
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - uptime-kuma.pc-ziegert.de
            - status-internal.pc-ziegert.de
          secretName: pc-ziegert-de-wildcard-cert
signal:
  enabled: true
  persistence:
    enabled: true
    storageClass: nfs-ssd
    accessModes:
      - ReadWriteMany